/* PLOP_INJECT_EXPORT */
export { either } from "./either";
export { isDivisible } from "./isDivisible";
export { findClosestFactor } from "./findClosestFactor";
export { findClosestDivisible } from "./findClosestDivisible";
export { isNumberInBetween } from "./isNumberInBetween";
export { isNumberBetween } from "./isNumberBetween";
export { findClosestTo } from "./findClosestTo";
export { findAntecedent } from "./findAntecedent";
export { toFixed } from "./toFixed";
export { toPercentage } from "./toPercentage";
export { cross } from "./cross/cross";
export { placeValueBetween } from "./placeValueBetween/placeValueBetween";
export { call } from "./call/call";
export { getAverageOf } from "./getAverageOf/getAverageOf";
export { getNextDivisibleOf } from "./getNextDivisibleOf/getNextDivisibleOf";
export { getPrevDivisibleOf } from "./getPrevDivisibleOf/getPrevDivisibleOf";
export { observerMixin } from "./observerMixin/observerMixin";
export { findRatio } from "./findRatio";
